services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper-loan
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka-loan
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper

  api:
    build:
      context: ./api
    container_name: loan-api
    environment:
      - SPARK_VERSION=3.5.3
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app  # Mount api folder to container
    depends_on:
      - kafka